/* The following code was generated by JFlex 1.4.3 on 28/5/23, 08:25 */

package code;
import static code.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 28/5/23, 08:25 from the specification file
 * <tt>C:/Users/alejo/Desktop/proyectos/utn/utn-lexer/src/main/java/code/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\12\2\0\1\2\22\0\1\21\1\35\1\25\3\3"+
    "\2\0\4\3\1\1\1\3\1\1\1\11\12\1\1\10\1\3\1\14"+
    "\1\3\1\26\2\3\2\1\1\40\1\36\1\44\11\1\1\37\1\43"+
    "\3\1\1\41\4\1\1\42\1\1\3\3\1\0\1\1\1\0\1\32"+
    "\1\47\1\45\1\30\1\24\1\13\1\34\1\4\1\16\1\50\1\20"+
    "\1\15\1\33\1\17\1\31\1\6\1\1\1\23\1\7\1\5\1\51"+
    "\1\27\1\53\1\22\1\52\1\46\3\3\43\0\1\3\25\0\1\3"+
    "\7\0\1\3\uff40\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\1\1\2\1\1\1\3\3\1\20\0\1\1\54\0"+
    "\2\1\100\0\1\1\65\0\1\4\16\0\1\1\7\0"+
    "\1\5\5\0\1\6\24\0\1\7\22\0\1\10\14\0"+
    "\1\11\2\0\1\12\2\13\1\0\1\14\1\15\1\16"+
    "\1\0\1\17\1\20\1\0\1\21\13\0\1\22\5\0"+
    "\1\23\5\0\1\24\13\0\1\25\2\0\1\26\10\0"+
    "\1\27\2\0\1\30\12\0\1\31\1\32\1\33\5\0"+
    "\1\34\1\35\1\36\1\0\1\37\1\40\1\0\1\41"+
    "\12\0\1\42\2\0\1\43\27\0\1\44\5\0\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\20\0\1\53\13\0"+
    "\1\54\3\0\1\55\1\56\4\0\1\57\2\0\1\60"+
    "\1\61\1\62\6\0\1\63\2\0\1\64\1\65\3\0"+
    "\1\66\1\0\1\67\6\0\1\70\2\0\1\71\6\0"+
    "\1\72\4\0\1\73\1\0\1\74\2\0\1\75\3\0"+
    "\1\76\6\0\1\77\1\100\1\0\1\101\2\0\1\102"+
    "\3\0\1\103\11\0\1\104\11\0\1\105\1\0\1\106"+
    "\1\107\3\0\1\110\1\111\1\112\1\0\1\113\4\0"+
    "\1\114\2\0\1\115\3\0\1\116\13\0\1\117\54\0"+
    "\1\120\2\0\1\121\15\0\1\122\4\0\1\120\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[645];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\204\0\334\0\u0108"+
    "\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8"+
    "\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04fc\0\u0528"+
    "\0\u0554\0\u0580\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c\0\u0688"+
    "\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8"+
    "\0\u0814\0\u0840\0\u086c\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948"+
    "\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8"+
    "\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08"+
    "\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68"+
    "\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8"+
    "\0\u0ef4\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\u0fd0\0\u0ffc\0\u1028"+
    "\0\u1054\0\u1080\0\u10ac\0\u10d8\0\u1104\0\u1130\0\u115c\0\u1188"+
    "\0\u11b4\0\u11e0\0\u120c\0\u1238\0\u1264\0\u1290\0\u12bc\0\u12e8"+
    "\0\u1314\0\u1340\0\u136c\0\u1398\0\u13c4\0\u13f0\0\u141c\0\u1448"+
    "\0\u1474\0\u14a0\0\u14cc\0\u14f8\0\u1524\0\u1550\0\u157c\0\u15a8"+
    "\0\u15d4\0\u1600\0\u162c\0\u1658\0\u1684\0\u16b0\0\u16dc\0\u1708"+
    "\0\u1734\0\u1760\0\u178c\0\u17b8\0\u17e4\0\u1810\0\u183c\0\u1868"+
    "\0\u1894\0\u18c0\0\u18ec\0\u1918\0\u1944\0\u1970\0\u199c\0\u19c8"+
    "\0\u19f4\0\u1a20\0\u1a4c\0\u1a78\0\u1aa4\0\u1ad0\0\u1afc\0\u1b28"+
    "\0\u1b54\0\u1b80\0\u1bac\0\u1bd8\0\u1c04\0\u1c30\0\u1c5c\0\u1c88"+
    "\0\u1cb4\0\u1ce0\0\u1d0c\0\u1d38\0\u1d64\0\u1d90\0\u1dbc\0\u1de8"+
    "\0\u1e14\0\u1e40\0\u1e6c\0\u1e98\0\u1ec4\0\u1ef0\0\u1f1c\0\u1f48"+
    "\0\u1f74\0\u1fa0\0\u1fcc\0\u1ff8\0\u2024\0\u2050\0\54\0\u207c"+
    "\0\u20a8\0\u20d4\0\u2100\0\u212c\0\u2158\0\u2184\0\u21b0\0\u21dc"+
    "\0\u2208\0\u2234\0\u2260\0\u228c\0\u22b8\0\u22e4\0\u2310\0\u233c"+
    "\0\u2368\0\u2394\0\u23c0\0\u23ec\0\u2418\0\54\0\u2444\0\u2470"+
    "\0\u249c\0\u24c8\0\u24f4\0\54\0\u2520\0\u254c\0\u2578\0\u25a4"+
    "\0\u25d0\0\u25fc\0\u2628\0\u2654\0\u2680\0\u26ac\0\u26d8\0\u2704"+
    "\0\u2730\0\u275c\0\u2788\0\u27b4\0\u27e0\0\u280c\0\u2838\0\u2864"+
    "\0\54\0\u2890\0\u28bc\0\u28e8\0\u2914\0\u2940\0\u296c\0\u2998"+
    "\0\u29c4\0\u29f0\0\u2a1c\0\u2a48\0\u2a74\0\u2aa0\0\u2acc\0\u2af8"+
    "\0\u2b24\0\u2b50\0\u2b7c\0\54\0\u2ba8\0\u2bd4\0\u2c00\0\u2c2c"+
    "\0\u2c58\0\u2c84\0\u2cb0\0\u2cdc\0\u2d08\0\u2d34\0\u2d60\0\u2d8c"+
    "\0\54\0\u2db8\0\u2de4\0\54\0\u2e10\0\u22e4\0\u2e3c\0\54"+
    "\0\54\0\54\0\u2e68\0\54\0\54\0\u2e94\0\54\0\u2ec0"+
    "\0\u2eec\0\u2f18\0\u2f44\0\u2f70\0\u2f9c\0\u2fc8\0\u2ff4\0\u3020"+
    "\0\u304c\0\u3078\0\54\0\u30a4\0\u30d0\0\u30fc\0\u3128\0\u3154"+
    "\0\54\0\u3180\0\u31ac\0\u31d8\0\u3204\0\u3230\0\54\0\u325c"+
    "\0\u3288\0\u32b4\0\u32e0\0\u330c\0\u3338\0\u3364\0\u3390\0\u33bc"+
    "\0\u33e8\0\u3414\0\54\0\u3440\0\u346c\0\54\0\u3498\0\u34c4"+
    "\0\u34f0\0\u351c\0\u3548\0\u3574\0\u35a0\0\u35cc\0\54\0\u35f8"+
    "\0\u3624\0\54\0\u3650\0\u367c\0\u36a8\0\u36d4\0\u3700\0\u372c"+
    "\0\u3758\0\u3784\0\u37b0\0\u37dc\0\54\0\54\0\54\0\u3808"+
    "\0\u3834\0\u3860\0\u388c\0\u38b8\0\54\0\54\0\54\0\u38e4"+
    "\0\54\0\54\0\u3910\0\54\0\u393c\0\u3968\0\u3994\0\u39c0"+
    "\0\u39ec\0\u3a18\0\u3a44\0\u3a70\0\u3a9c\0\u3ac8\0\54\0\u3af4"+
    "\0\u3b20\0\54\0\u3b4c\0\u3b78\0\u3ba4\0\u3bd0\0\u3bfc\0\u3c28"+
    "\0\u3c54\0\u3c80\0\u3cac\0\u3cd8\0\u3d04\0\u3d30\0\u3d5c\0\u3d88"+
    "\0\u3db4\0\u3de0\0\u3e0c\0\u3e38\0\u3e64\0\u3e90\0\u3ebc\0\u3ee8"+
    "\0\u3f14\0\54\0\u3f40\0\u3f6c\0\u3f98\0\u3fc4\0\u3ff0\0\54"+
    "\0\54\0\54\0\54\0\54\0\54\0\u401c\0\u4048\0\u4074"+
    "\0\u40a0\0\u40cc\0\u40f8\0\u4124\0\u4150\0\u417c\0\u41a8\0\u41d4"+
    "\0\u4200\0\u422c\0\u4258\0\u4284\0\u42b0\0\54\0\u42dc\0\u4308"+
    "\0\u4334\0\u4360\0\u438c\0\u43b8\0\u43e4\0\u4410\0\u443c\0\u4468"+
    "\0\u4494\0\54\0\u44c0\0\u44ec\0\u4518\0\54\0\54\0\u4544"+
    "\0\u4570\0\u459c\0\u45c8\0\54\0\u45f4\0\u4620\0\54\0\54"+
    "\0\54\0\u464c\0\u4678\0\u46a4\0\u46d0\0\u46fc\0\u4728\0\54"+
    "\0\u4754\0\u4780\0\54\0\54\0\u47ac\0\u47d8\0\u4804\0\54"+
    "\0\u4830\0\54\0\u485c\0\u4888\0\u48b4\0\u48e0\0\u490c\0\u4938"+
    "\0\54\0\u4964\0\u4990\0\54\0\u49bc\0\u49e8\0\u4a14\0\u4a40"+
    "\0\u4a6c\0\u4a98\0\54\0\u4ac4\0\u4af0\0\u4b1c\0\u4b48\0\54"+
    "\0\u4b74\0\54\0\u4ba0\0\u4bcc\0\54\0\u4bf8\0\u4c24\0\u4c50"+
    "\0\54\0\u4c7c\0\u4ca8\0\u4cd4\0\u4d00\0\u4d2c\0\u4d58\0\54"+
    "\0\54\0\u4d84\0\54\0\u4db0\0\u4ddc\0\54\0\u4e08\0\u4e34"+
    "\0\u4e60\0\54\0\u4e8c\0\u4eb8\0\u4ee4\0\u4f10\0\u4f3c\0\u4f68"+
    "\0\u4f94\0\u4fc0\0\u4fec\0\54\0\u5018\0\u5044\0\u5070\0\u509c"+
    "\0\u50c8\0\u50f4\0\u5120\0\u514c\0\u5178\0\54\0\u51a4\0\54"+
    "\0\54\0\u51d0\0\u51fc\0\u5228\0\54\0\54\0\54\0\u5254"+
    "\0\54\0\u5280\0\u52ac\0\u52d8\0\u5304\0\54\0\u5330\0\u535c"+
    "\0\54\0\u5388\0\u53b4\0\u53e0\0\54\0\u540c\0\u5438\0\u5464"+
    "\0\u5490\0\u54bc\0\u54e8\0\u5514\0\u5540\0\u556c\0\u5598\0\u55c4"+
    "\0\54\0\u55f0\0\u561c\0\u5648\0\u5674\0\u56a0\0\u56cc\0\u56f8"+
    "\0\u5724\0\u5750\0\u577c\0\u57a8\0\u57d4\0\u5800\0\u582c\0\u5858"+
    "\0\u5884\0\u58b0\0\u58dc\0\u5908\0\u5934\0\u5960\0\u598c\0\u59b8"+
    "\0\u59e4\0\u5a10\0\u5a3c\0\u5a68\0\u5a94\0\u5ac0\0\u5aec\0\u5b18"+
    "\0\u5b44\0\u5b70\0\u5b9c\0\u5bc8\0\u5bf4\0\u5c20\0\u5c4c\0\u5c78"+
    "\0\u5ca4\0\u5cd0\0\u5cfc\0\u5d28\0\u5d54\0\54\0\u5d80\0\u5dac"+
    "\0\54\0\u5dd8\0\u5e04\0\u5e30\0\u5e5c\0\u5e88\0\u5eb4\0\u5ee0"+
    "\0\u5f0c\0\u5f38\0\u5f64\0\u5f90\0\u5fbc\0\u5fe8\0\u5d54\0\u6014"+
    "\0\u6040\0\u606c\0\u6098\0\u5f38\0\u5f64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[645];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\5\3\1\6\1\7"+
    "\1\10\4\3\1\4\4\3\1\2\25\3\55\0\13\3"+
    "\1\0\11\3\1\0\25\3\1\0\1\3\1\4\7\3"+
    "\1\4\1\3\1\0\4\3\1\4\4\3\1\0\25\3"+
    "\1\0\4\3\1\7\6\3\1\0\11\3\1\0\25\3"+
    "\1\0\4\3\1\11\6\3\1\0\11\3\1\0\25\3"+
    "\4\0\1\12\1\13\1\14\1\15\1\0\1\16\1\0"+
    "\1\17\1\0\1\20\1\21\4\0\1\22\1\23\2\0"+
    "\1\24\2\0\1\25\1\26\1\0\1\27\7\0\1\30"+
    "\4\0\1\31\2\0\5\3\1\32\5\3\1\0\11\3"+
    "\1\0\25\3\31\0\1\33\26\0\1\34\6\0\1\35"+
    "\2\0\1\36\15\0\1\37\12\0\1\40\10\0\1\41"+
    "\25\0\1\42\26\0\1\43\10\0\1\44\5\0\1\45"+
    "\24\0\1\46\6\0\1\47\1\50\1\51\1\52\3\0"+
    "\1\53\1\0\1\54\1\55\4\0\1\56\1\57\2\0"+
    "\1\60\2\0\1\61\1\62\11\0\1\63\4\0\1\64"+
    "\17\0\1\65\53\0\1\66\42\0\1\67\11\0\1\70"+
    "\13\0\1\71\51\0\1\72\41\0\1\73\13\0\1\74"+
    "\36\0\1\75\60\0\1\76\4\0\1\77\16\0\1\100"+
    "\1\0\1\101\26\0\1\102\65\0\1\103\33\0\1\104"+
    "\12\0\1\105\46\0\1\106\30\0\6\3\1\107\1\110"+
    "\3\3\1\0\11\3\1\0\25\3\15\0\1\111\62\0"+
    "\1\112\60\0\1\113\27\0\1\114\71\0\1\115\61\0"+
    "\1\116\53\0\1\117\45\0\1\120\53\0\1\121\6\0"+
    "\1\122\54\0\1\123\65\0\1\124\31\0\1\125\61\0"+
    "\1\126\26\0\1\127\6\0\1\130\2\0\1\131\15\0"+
    "\1\132\12\0\1\133\10\0\1\134\25\0\1\135\26\0"+
    "\1\136\10\0\1\137\5\0\1\140\24\0\1\141\20\0"+
    "\1\142\53\0\1\143\42\0\1\144\11\0\1\145\13\0"+
    "\1\146\51\0\1\147\41\0\1\150\13\0\1\151\36\0"+
    "\1\152\60\0\1\153\4\0\1\154\16\0\1\155\1\0"+
    "\1\156\26\0\1\157\45\0\1\160\12\0\1\161\46\0"+
    "\1\162\52\0\1\163\37\0\1\164\7\0\1\165\60\0"+
    "\1\166\42\0\1\167\46\0\1\170\23\0\1\171\74\0"+
    "\1\172\5\0\1\173\54\0\1\174\23\0\1\175\51\0"+
    "\1\176\30\0\1\177\76\0\1\200\32\0\1\201\51\0"+
    "\1\202\76\0\1\203\62\0\1\204\21\0\1\205\54\0"+
    "\1\206\24\0\1\207\52\0\1\210\22\0\7\3\1\110"+
    "\3\3\1\0\11\3\1\0\25\3\1\0\10\3\1\211"+
    "\2\3\1\0\11\3\1\0\25\3\30\0\1\212\55\0"+
    "\1\213\52\0\1\214\37\0\1\215\67\0\1\216\52\0"+
    "\1\217\42\0\1\220\66\0\1\221\45\0\1\222\34\0"+
    "\1\223\54\0\1\224\52\0\1\225\65\0\1\226\51\0"+
    "\1\227\62\0\1\230\60\0\1\231\27\0\1\232\71\0"+
    "\1\233\61\0\1\234\53\0\1\235\45\0\1\236\53\0"+
    "\1\237\6\0\1\240\54\0\1\241\65\0\1\242\31\0"+
    "\1\243\53\0\1\244\37\0\1\245\70\0\1\246\42\0"+
    "\1\247\46\0\1\250\23\0\1\251\74\0\1\252\5\0"+
    "\1\253\54\0\1\254\23\0\1\255\51\0\1\256\30\0"+
    "\1\257\76\0\1\260\32\0\1\261\51\0\1\262\76\0"+
    "\1\263\30\0\1\264\54\0\1\265\24\0\1\266\52\0"+
    "\1\267\30\0\1\270\51\0\1\271\66\0\1\272\66\0"+
    "\1\273\51\0\1\274\53\0\1\275\56\0\1\276\45\0"+
    "\1\277\50\0\1\300\34\0\1\301\65\0\1\302\61\0"+
    "\1\303\45\0\1\304\60\0\1\305\35\0\1\306\52\0"+
    "\1\307\65\0\1\310\75\0\1\311\65\0\1\312\53\0"+
    "\1\313\34\0\1\314\43\0\1\315\31\0\10\3\1\316"+
    "\2\3\1\0\11\3\1\0\25\3\24\0\1\317\57\0"+
    "\1\320\30\0\1\321\72\0\1\322\100\0\1\323\54\0"+
    "\1\324\25\0\1\325\55\0\1\326\51\0\1\327\53\0"+
    "\1\330\44\0\1\331\14\0\1\332\37\0\1\333\7\0"+
    "\1\334\57\0\1\335\51\0\1\336\55\0\1\337\52\0"+
    "\1\340\37\0\1\341\67\0\1\342\52\0\1\343\42\0"+
    "\1\344\66\0\1\345\45\0\1\346\34\0\1\347\54\0"+
    "\1\350\52\0\1\351\65\0\1\352\43\0\1\353\51\0"+
    "\1\354\101\0\1\355\51\0\1\356\53\0\1\357\56\0"+
    "\1\360\45\0\1\361\50\0\1\362\34\0\1\363\65\0"+
    "\1\364\61\0\1\365\45\0\1\366\60\0\1\367\35\0"+
    "\1\370\52\0\1\371\65\0\1\372\107\0\1\373\53\0"+
    "\1\374\34\0\1\375\43\0\1\376\35\0\1\377\64\0"+
    "\1\u0100\56\0\1\u0101\50\0\1\u0102\60\0\1\u0103\2\0"+
    "\1\u0104\50\0\1\u0105\54\0\1\u0106\101\0\1\u0107\33\0"+
    "\1\u0108\36\0\1\u0109\67\0\1\u010a\67\0\1\u010b\32\0"+
    "\1\u010c\52\0\1\u010d\61\0\1\u010e\54\0\1\u010f\62\0"+
    "\1\u0110\40\0\1\u0111\50\0\1\u0112\54\0\1\u0113\55\0"+
    "\1\u0114\25\0\1\u0115\11\u0116\1\3\1\u0116\1\u0115\11\u0116"+
    "\1\u0115\25\u0116\23\0\1\u0117\56\0\1\u0118\53\0\1\u0119"+
    "\53\0\1\u011a\33\0\1\u011b\73\0\1\u011c\53\0\1\u011d"+
    "\32\0\1\u011e\74\0\1\u011f\51\0\1\u0120\52\0\1\u0121"+
    "\61\0\1\u0122\55\0\1\u0123\44\0\1\u0124\57\0\1\u0125"+
    "\30\0\1\u0126\72\0\1\u0127\100\0\1\u0128\54\0\1\u0129"+
    "\25\0\1\u012a\55\0\1\u012b\51\0\1\u012c\53\0\1\u012d"+
    "\44\0\1\u012e\14\0\1\u012f\37\0\1\u0130\7\0\1\u0131"+
    "\57\0\1\u0132\26\0\1\u0133\64\0\1\u0134\53\0\1\u0135"+
    "\60\0\1\u0136\2\0\1\u0137\50\0\1\u0138\54\0\1\u0139"+
    "\101\0\1\u013a\33\0\1\u013b\36\0\1\u013c\67\0\1\u013d"+
    "\67\0\1\u013e\32\0\1\u013f\52\0\1\u0140\61\0\1\u0141"+
    "\54\0\1\u0142\47\0\1\u0143\50\0\1\u0144\54\0\1\u0145"+
    "\55\0\1\u0146\44\0\1\u0147\41\0\1\u0148\70\0\1\u0149"+
    "\77\0\1\u014a\40\0\1\u014b\25\0\1\u014c\76\0\1\u014d"+
    "\1\u014e\50\0\1\u014f\20\0\1\u0150\13\0\1\u0151\72\0"+
    "\1\u0152\55\0\1\u0153\1\u0154\37\0\1\u0155\45\0\1\u0156"+
    "\76\0\1\u0157\44\0\1\u0158\61\0\1\u0159\64\0\1\u015a"+
    "\27\0\1\u015b\54\0\1\u015c\34\0\12\u0115\1\0\41\u0115"+
    "\26\0\1\u015d\53\0\1\u015e\53\0\1\u015f\34\0\1\u0160"+
    "\76\0\1\u0161\40\0\1\u0162\60\0\1\u0163\52\0\1\u0164"+
    "\56\0\1\u0165\53\0\1\u0166\53\0\1\u0167\33\0\1\u0168"+
    "\73\0\1\u0169\53\0\1\u016a\32\0\1\u016b\74\0\1\u016c"+
    "\51\0\1\u016d\52\0\1\u016e\61\0\1\u016f\55\0\1\u0170"+
    "\37\0\1\u0171\41\0\1\u0172\114\0\1\u0173\40\0\1\u0174"+
    "\25\0\1\u0175\77\0\1\u0176\50\0\1\u0177\20\0\1\u0178"+
    "\13\0\1\u0179\72\0\1\u017a\56\0\1\u017b\37\0\1\u017c"+
    "\45\0\1\u017d\76\0\1\u017e\44\0\1\u017f\61\0\1\u0180"+
    "\40\0\1\u0181\54\0\1\u0182\66\0\1\u0183\45\0\1\u0184"+
    "\44\0\1\u0185\62\0\1\u0186\61\0\1\u0187\53\0\1\u0188"+
    "\53\0\1\u0189\70\0\1\u018a\21\0\1\u018b\54\0\1\u018c"+
    "\67\0\1\u018d\70\0\1\u018e\30\0\1\u018f\36\0\1\u0190"+
    "\111\0\1\u0191\34\0\1\u0192\74\0\1\u0193\47\0\1\u0194"+
    "\44\0\1\u0195\24\0\1\u0196\72\0\1\u0197\55\0\1\u0198"+
    "\53\0\1\u0199\53\0\1\u019a\53\0\1\u019b\53\0\1\u019c"+
    "\53\0\1\u019d\34\0\1\u019e\76\0\1\u019f\40\0\1\u01a0"+
    "\60\0\1\u01a1\61\0\1\u01a2\45\0\1\u01a3\53\0\1\u01a4"+
    "\61\0\1\u01a5\53\0\1\u01a6\70\0\1\u01a7\21\0\1\u01a8"+
    "\54\0\1\u01a9\104\0\1\u01aa\30\0\1\u01ab\36\0\1\u01ac"+
    "\111\0\1\u01ad\34\0\1\u01ae\74\0\1\u01af\40\0\1\u01b0"+
    "\24\0\1\u01b1\101\0\1\u01b2\53\0\1\u01b3\36\0\1\u01b4"+
    "\65\0\1\u01b5\40\0\1\u01b6\55\0\1\u01b7\41\0\1\u01b8"+
    "\116\0\1\u01b9\31\0\1\u01ba\34\0\1\u01bb\51\0\1\u01bc"+
    "\116\0\1\u01bd\31\0\1\u01be\53\0\1\u01bf\32\0\1\u01c0"+
    "\116\0\1\u01c1\47\0\1\u01c2\13\0\1\u01c3\75\0\1\u01c4"+
    "\72\0\1\u01c5\32\0\1\u01c6\55\0\1\u01c7\53\0\1\u01c8"+
    "\53\0\1\u01c9\60\0\1\u01ca\53\0\1\u01cb\50\0\1\u01cc"+
    "\40\0\1\u01cd\55\0\1\u01ce\104\0\1\u01cf\31\0\1\u01d0"+
    "\34\0\1\u01d1\114\0\1\u01d2\31\0\1\u01d3\53\0\1\u01d4"+
    "\32\0\1\u01d5\116\0\1\u01d6\7\0\1\u01d7\75\0\1\u01d8"+
    "\51\0\1\u01d9\55\0\1\u01da\44\0\1\u01db\51\0\1\u01dc"+
    "\43\0\1\u01dd\53\0\1\u01de\100\0\1\u01df\45\0\1\u01e0"+
    "\55\0\1\u01e1\57\0\1\u01e2\45\0\1\u01e3\55\0\1\u01e4"+
    "\51\0\1\u01e5\50\0\1\u01e6\37\0\1\u01e7\53\0\1\u01e8"+
    "\113\0\1\u01e9\32\0\1\u01ea\55\0\1\u01eb\42\0\1\u01ec"+
    "\43\0\1\u01ed\53\0\1\u01ee\72\0\1\u01ef\55\0\1\u01f0"+
    "\51\0\1\u01f1\55\0\1\u01f2\51\0\1\u01f3\34\0\1\u01f4"+
    "\74\0\1\u01f5\45\0\1\u01f6\51\0\1\u01f7\67\0\1\u01f8"+
    "\47\0\1\u01f9\46\0\1\u01fa\77\0\1\u01fb\27\0\1\u01fc"+
    "\77\0\1\u01fd\53\0\1\u01fe\40\0\1\u01ff\47\0\1\u0200"+
    "\53\0\1\u0201\32\0\1\u0202\74\0\1\u0203\43\0\1\u0204"+
    "\67\0\1\u0205\47\0\1\u0206\72\0\1\u0207\53\0\1\u0208"+
    "\53\0\1\u0209\34\0\1\u020a\35\0\1\u020b\52\0\1\u020c"+
    "\113\0\1\u020d\17\0\1\u020e\45\0\1\u020f\61\0\1\u0210"+
    "\45\0\1\u0211\53\0\1\u0212\71\0\1\u0213\56\0\1\u0214"+
    "\34\0\1\u0215\113\0\1\u0216\11\0\1\u0217\53\0\1\u0218"+
    "\53\0\1\u0219\52\0\1\u021a\54\0\1\u021b\63\0\1\u021c"+
    "\54\0\1\u021d\63\0\1\u021e\43\0\1\u021f\63\0\1\u0220"+
    "\53\0\1\u0221\32\0\1\u0222\53\0\1\u0223\63\0\1\u0224"+
    "\64\0\1\u0225\53\0\1\u0226\53\0\1\u0227\50\0\1\u0228"+
    "\56\0\1\u0229\51\0\1\u022a\44\0\1\u022b\53\0\1\u022c"+
    "\54\0\1\u022d\63\0\1\u022e\51\0\1\u022f\53\0\1\u0230"+
    "\55\0\1\u0231\51\0\1\u0232\53\0\1\u0233\74\0\1\u0234"+
    "\34\0\1\u0235\40\0\1\u0236\63\0\1\u0237\53\0\1\u0238"+
    "\45\0\1\u0239\46\0\1\u023a\67\0\1\u023b\53\0\1\u023c"+
    "\53\0\1\u023d\54\0\1\u023e\41\0\1\u023f\53\0\1\u0240"+
    "\66\0\1\u0241\31\0\1\u0242\6\0\1\u0243\1\u0244\47\0"+
    "\1\u0245\53\0\1\u0246\50\0\1\u0243\53\0\1\u0247\63\0"+
    "\1\u0248\63\0\1\u0249\53\0\1\u024a\34\0\1\u024b\63\0"+
    "\1\u024c\36\0\1\u024d\2\0\1\u024e\3\u024d\1\0\1\u024d"+
    "\1\0\1\u024f\1\u0250\4\u024d\1\0\3\u024d\2\0\6\u024d"+
    "\1\0\16\u024d\1\0\1\u0251\2\0\1\u0252\3\u0251\1\0"+
    "\1\u0251\1\0\1\u0253\1\u0254\4\u0251\1\0\3\u0251\2\0"+
    "\6\u0251\1\0\16\u0251\7\0\1\u0255\1\u0256\62\0\1\165"+
    "\35\0\1\u024d\2\0\1\u024e\3\u024d\1\0\1\u024d\1\0"+
    "\1\u024f\1\0\4\u024d\1\0\3\u024d\1\u0257\1\0\6\u024d"+
    "\1\0\16\u024d\1\0\1\u024d\2\0\1\u024e\1\u024f\2\u024d"+
    "\1\0\1\u024d\1\0\1\u024f\1\0\4\u024d\1\0\3\u024d"+
    "\1\u0257\1\0\6\u024d\1\0\16\u024d\1\0\1\u024d\2\0"+
    "\1\u024e\1\u0258\2\u024d\1\0\1\u024d\1\0\1\u024f\1\0"+
    "\4\u024d\1\0\3\u024d\1\u0257\1\0\6\u024d\1\0\16\u024d"+
    "\16\0\1\u0259\36\0\1\u0251\2\0\1\u0252\3\u0251\1\0"+
    "\1\u0251\1\0\1\u0253\1\0\4\u0251\1\0\3\u0251\1\u025a"+
    "\1\0\6\u0251\1\0\16\u0251\1\0\1\u0251\2\0\1\u0252"+
    "\1\u0253\2\u0251\1\0\1\u0251\1\0\1\u0253\1\0\4\u0251"+
    "\1\0\3\u0251\1\u025a\1\0\6\u0251\1\0\16\u0251\1\0"+
    "\1\u0251\2\0\1\u0252\1\u025b\2\u0251\1\0\1\u0251\1\0"+
    "\1\u0253\1\0\4\u0251\1\0\3\u0251\1\u025a\1\0\6\u0251"+
    "\1\0\16\u0251\27\0\1\u025c\34\0\1\u0256\54\0\1\u025d"+
    "\63\0\1\u025e\33\0\1\u024d\2\0\1\u024e\1\u024d\1\u025f"+
    "\1\u024d\1\0\1\u024d\1\0\1\u024f\1\0\4\u024d\1\0"+
    "\3\u024d\1\u0257\1\0\6\u024d\1\0\16\u024d\33\0\1\u0260"+
    "\41\0\1\u0261\33\0\1\u0251\2\0\1\u0252\1\u0251\1\u0262"+
    "\1\u0251\1\0\1\u0251\1\0\1\u0253\1\0\4\u0251\1\0"+
    "\3\u0251\1\u025a\1\0\6\u0251\1\0\16\u0251\16\0\1\u0263"+
    "\46\0\1\u0264\53\0\1\u0265\43\0\1\u024d\2\0\1\u024e"+
    "\2\u024d\1\u0266\1\u0267\1\u024d\1\0\1\u024f\1\0\4\u024d"+
    "\1\0\3\u024d\1\u0257\1\0\6\u024d\1\0\16\u024d\32\0"+
    "\1\u0268\32\0\1\u0269\43\0\1\u0251\2\0\1\u0252\2\u0251"+
    "\1\u026a\1\u026b\1\u0251\1\0\1\u0253\1\0\4\u0251\1\0"+
    "\3\u0251\1\u025a\1\0\6\u0251\1\0\16\u0251\30\0\1\u026c"+
    "\23\0\12\u026d\1\0\41\u026d\26\0\1\u026e\26\0\1\u024d"+
    "\2\0\1\u024e\3\u024d\1\u0267\1\u024d\1\0\1\u024f\1\0"+
    "\4\u024d\1\0\3\u024d\1\u0257\1\0\6\u024d\1\0\16\u024d"+
    "\11\0\1\u026f\76\0\1\u0270\45\0\1\u0271\26\0\1\u0251"+
    "\2\0\1\u0252\3\u0251\1\u026b\1\u0251\1\0\1\u0253\1\0"+
    "\4\u0251\1\0\3\u0251\1\u025a\1\0\6\u0251\1\0\16\u0251"+
    "\11\0\1\u0272\66\0\1\u0273\27\0\12\u026d\1\0\12\u026d"+
    "\1\u0274\26\u026d\11\0\1\u0275\66\0\1\u0276\40\0\1\u0277"+
    "\73\0\1\u0278\22\0\12\u026d\1\0\6\u026d\1\u0279\3\u026d"+
    "\1\u0274\26\u026d\12\u027a\1\0\41\u027a\30\0\1\u014d\23\0"+
    "\12\u027b\1\0\41\u027b\30\0\1\u0153\23\0\11\u026d\1\u027c"+
    "\1\0\12\u026d\1\u0274\26\u026d\12\u027a\1\0\12\u027a\1\u027d"+
    "\26\u027a\12\u027b\1\0\12\u027b\1\u027e\26\u027b\12\u026d\1\0"+
    "\12\u026d\1\u0274\1\u027f\25\u026d\12\u027a\1\0\6\u027a\1\u0280"+
    "\3\u027a\1\u027d\26\u027a\12\u027b\1\0\6\u027b\1\u0281\3\u027b"+
    "\1\u027e\26\u027b\11\u027a\1\u0282\1\0\12\u027a\1\u027d\26\u027a"+
    "\11\u027b\1\u0283\1\0\12\u027b\1\u027e\26\u027b\12\u027a\1\0"+
    "\12\u027a\1\u027d\1\u0284\25\u027a\12\u027b\1\0\12\u027b\1\u027e"+
    "\1\u0285\25\u027b";

  private static int [] zzUnpackTrans() {
    int [] result = new int[24772];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\7\1\20\0\1\1\54\0\2\1\100\0"+
    "\1\1\65\0\1\11\16\0\1\1\7\0\1\11\5\0"+
    "\1\11\24\0\1\11\22\0\1\11\14\0\1\11\2\0"+
    "\1\11\2\1\1\0\3\11\1\0\2\11\1\0\1\11"+
    "\13\0\1\11\5\0\1\11\5\0\1\11\13\0\1\11"+
    "\2\0\1\11\10\0\1\11\2\0\1\11\12\0\3\11"+
    "\5\0\3\11\1\0\2\11\1\0\1\11\12\0\1\11"+
    "\2\0\1\11\27\0\1\11\5\0\6\11\20\0\1\11"+
    "\13\0\1\11\3\0\2\11\4\0\1\11\2\0\3\11"+
    "\6\0\1\11\2\0\2\11\3\0\1\11\1\0\1\11"+
    "\6\0\1\11\2\0\1\11\6\0\1\11\4\0\1\11"+
    "\1\0\1\11\2\0\1\11\3\0\1\11\6\0\2\11"+
    "\1\0\1\11\2\0\1\11\3\0\1\11\11\0\1\11"+
    "\11\0\1\11\1\0\2\11\3\0\3\11\1\0\1\11"+
    "\4\0\1\11\2\0\1\11\3\0\1\11\13\0\1\11"+
    "\54\0\1\11\2\0\1\11\15\0\1\1\4\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[645];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 63: 
          { lexeme=yytext(); return AperturaCopyright;
          }
        case 83: break;
        case 77: 
          { lexeme=yytext(); return AperturaInformalTable;
          }
        case 84: break;
        case 57: 
          { lexeme=yytext(); return AperturaAbstract;
          }
        case 85: break;
        case 4: 
          { lexeme=yytext(); return AperturaRow;
          }
        case 86: break;
        case 30: 
          { lexeme=yytext(); return CierreTitulo;
          }
        case 87: break;
        case 2: 
          { /*IGNORE*/
          }
        case 88: break;
        case 5: 
          { lexeme=yytext(); return AperturaPara;
          }
        case 89: break;
        case 71: 
          { lexeme=yytext(); return AperturaMediaObject;
          }
        case 90: break;
        case 79: 
          { lexeme=yytext(); return EncabezadoXML;
          }
        case 91: break;
        case 73: 
          { lexeme=yytext(); return CierreVideoobject;
          }
        case 92: break;
        case 70: 
          { lexeme=yytext(); return AperturaVideobject;
          }
        case 93: break;
        case 19: 
          { lexeme=yytext(); return CierreSeccion;
          }
        case 94: break;
        case 58: 
          { lexeme=yytext(); return CierreListItem;
          }
        case 95: break;
        case 39: 
          { lexeme=yytext(); return AperturaSurname;
          }
        case 96: break;
        case 65: 
          { lexeme=yytext(); return CierreFirstName;
          }
        case 97: break;
        case 53: 
          { lexeme=yytext(); return CierreAddress;
          }
        case 98: break;
        case 78: 
          { lexeme=yytext(); return CierreInformalTable;
          }
        case 99: break;
        case 75: 
          { lexeme=yytext(); return AperturaItemizedList;
          }
        case 100: break;
        case 10: 
          { lexeme=yytext(); return AperturaYear;
          }
        case 101: break;
        case 25: 
          { lexeme=yytext(); return AperturaHolder;
          }
        case 102: break;
        case 44: 
          { lexeme=yytext(); return AperturaEntrybl;
          }
        case 103: break;
        case 42: 
          { lexeme=yytext(); return CierreStreet;
          }
        case 104: break;
        case 81: 
          { lexeme=yytext(); return Videodata;
          }
        case 105: break;
        case 38: 
          { lexeme=yytext(); return AperturaSection;
          }
        case 106: break;
        case 68: 
          { lexeme=yytext(); return CierreSimpleSect;
          }
        case 107: break;
        case 61: 
          { lexeme=yytext(); return AperturaFirstName;
          }
        case 108: break;
        case 72: 
          { lexeme=yytext(); return CierreImageobject;
          }
        case 109: break;
        case 13: 
          { lexeme=yytext(); return AperturaTfoot;
          }
        case 110: break;
        case 56: 
          { lexeme=yytext(); return AperturaEmphasis;
          }
        case 111: break;
        case 48: 
          { lexeme=yytext(); return CierreSimPara;
          }
        case 112: break;
        case 29: 
          { lexeme=yytext(); return CierreTfoot;
          }
        case 113: break;
        case 14: 
          { lexeme=yytext(); return AperturaTitulo;
          }
        case 114: break;
        case 66: 
          { lexeme=yytext(); return CierreImportant;
          }
        case 115: break;
        case 76: 
          { lexeme=yytext(); return CierreItemizedList;
          }
        case 116: break;
        case 60: 
          { lexeme=yytext(); return CierreAbstract;
          }
        case 117: break;
        case 43: 
          { lexeme=yytext(); return CierreAuthor;
          }
        case 118: break;
        case 74: 
          { lexeme=yytext(); return CierreMediaObject;
          }
        case 119: break;
        case 54: 
          { lexeme=yytext(); return CierreComment;
          }
        case 120: break;
        case 17: 
          { lexeme=yytext(); return AperturaState;
          }
        case 121: break;
        case 21: 
          { lexeme=yytext(); return CierreCity;
          }
        case 122: break;
        case 33: 
          { lexeme=yytext(); return CierreState;
          }
        case 123: break;
        case 45: 
          { lexeme=yytext(); return AperturaArticulo;
          }
        case 124: break;
        case 6: 
          { lexeme=yytext(); return AperturaSeccion;
          }
        case 125: break;
        case 41: 
          { lexeme=yytext(); return CierreTgroup;
          }
        case 126: break;
        case 20: 
          { lexeme=yytext(); return CierreInfo;
          }
        case 127: break;
        case 46: 
          { lexeme=yytext(); return AperturaAddress;
          }
        case 128: break;
        case 64: 
          { lexeme=yytext(); return AperturaSimpleSect;
          }
        case 129: break;
        case 62: 
          { lexeme=yytext(); return AperturaImportant;
          }
        case 130: break;
        case 27: 
          { lexeme=yytext(); return AperturaStreet;
          }
        case 131: break;
        case 15: 
          { lexeme=yytext(); return AperturaTbody;
          }
        case 132: break;
        case 1: 
          { lexeme=yytext(); return Texto;
          }
        case 133: break;
        case 31: 
          { lexeme=yytext(); return CierreTbody;
          }
        case 134: break;
        case 37: 
          { lexeme=yytext(); return AperturaSimPara;
          }
        case 135: break;
        case 34: 
          { lexeme=yytext(); return CierreEntry;
          }
        case 136: break;
        case 12: 
          { lexeme=yytext(); return AperturaThead;
          }
        case 137: break;
        case 3: 
          { return Linea;
          }
        case 138: break;
        case 36: 
          { lexeme=yytext(); return AperturaAuthor;
          }
        case 139: break;
        case 28: 
          { lexeme=yytext(); return CierreThead;
          }
        case 140: break;
        case 59: 
          { lexeme=yytext(); return CierreEmphasis;
          }
        case 141: break;
        case 18: 
          { lexeme=yytext(); return CierrePara;
          }
        case 142: break;
        case 55: 
          { lexeme=yytext(); return AperturaListItem;
          }
        case 143: break;
        case 67: 
          { lexeme=yytext(); return CierreCopyright;
          }
        case 144: break;
        case 9: 
          { lexeme=yytext(); return AperturaCity;
          }
        case 145: break;
        case 16: 
          { lexeme=yytext(); return AperturaPhone;
          }
        case 146: break;
        case 35: 
          { lexeme=yytext(); return CierreEmail;
          }
        case 147: break;
        case 23: 
          { lexeme=yytext(); return AperturaEntry;
          }
        case 148: break;
        case 32: 
          { lexeme=yytext(); return CierrePhone;
          }
        case 149: break;
        case 26: 
          { lexeme=yytext(); return AperturaTgroup;
          }
        case 150: break;
        case 50: 
          { lexeme=yytext(); return CierreSurname;
          }
        case 151: break;
        case 8: 
          { lexeme=yytext(); return AperturaInfo;
          }
        case 152: break;
        case 7: 
          { lexeme=yytext(); return CierreRow;
          }
        case 153: break;
        case 69: 
          { lexeme=yytext(); return AperturaImageobject;
          }
        case 154: break;
        case 24: 
          { lexeme=yytext(); return AperturaEmail;
          }
        case 155: break;
        case 82: 
          { lexeme=yytext(); return Link;
          }
        case 156: break;
        case 47: 
          { lexeme=yytext(); return AperturaComment;
          }
        case 157: break;
        case 52: 
          { lexeme=yytext(); return CierreArticulo;
          }
        case 158: break;
        case 51: 
          { lexeme=yytext(); return CierreEntrybl;
          }
        case 159: break;
        case 40: 
          { lexeme=yytext(); return CierreHolder;
          }
        case 160: break;
        case 49: 
          { lexeme=yytext(); return CierreSection;
          }
        case 161: break;
        case 22: 
          { lexeme=yytext(); return CierreYear;
          }
        case 162: break;
        case 11: 
          { lexeme=yytext(); return Url;
          }
        case 163: break;
        case 80: 
          { lexeme=yytext(); return Imagedata;
          }
        case 164: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
