
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 01 23:42:49 ART 2023
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AperturaTbody = 62;
  public static final int CierreEntry = 67;
  public static final int CierreSection = 20;
  public static final int Imagedata = 75;
  public static final int CierreRow = 65;
  public static final int CierreTitulo = 80;
  public static final int AperturaThead = 58;
  public static final int CierreSurname = 47;
  public static final int EncabezadoXML = 82;
  public static final int AperturaHolder = 50;
  public static final int CierreEmail = 43;
  public static final int CierreTgroup = 57;
  public static final int AperturaYear = 48;
  public static final int CierreCity = 37;
  public static final int AperturaSection = 21;
  public static final int AperturaFirstName = 44;
  public static final int CierreTituloArticle = 81;
  public static final int CierrePara = 12;
  public static final int AperturaImageobject = 72;
  public static final int CierreItemizedList = 16;
  public static final int CierreVideoobject = 71;
  public static final int AperturaEmphasis = 52;
  public static final int CierreAddress = 8;
  public static final int CierreInformalTable = 2;
  public static final int CierreEmphasis = 53;
  public static final int AperturaImportant = 15;
  public static final int CierreTbody = 63;
  public static final int AperturaCity = 36;
  public static final int AperturaSurname = 46;
  public static final int AperturaAuthor = 30;
  public static final int AperturaSimpleSect = 28;
  public static final int AperturaPara = 13;
  public static final int AperturaTfoot = 60;
  public static final int CierreThead = 59;
  public static final int CierreStreet = 35;
  public static final int AperturaPhone = 40;
  public static final int CierreLink = 55;
  public static final int AperturaArticulo = 22;
  public static final int CierreFirstName = 45;
  public static final int AperturaListItem = 76;
  public static final int CierreInfo = 18;
  public static final int AperturaInformalTable = 3;
  public static final int CierreArticulo = 23;
  public static final int AperturaAddress = 9;
  public static final int CierreListItem = 77;
  public static final int CierreHolder = 51;
  public static final int CierreDate = 4;
  public static final int Videodata = 74;
  public static final int CierreEntrytbl = 69;
  public static final int AperturaAbstract = 26;
  public static final int CierreImportant = 14;
  public static final int AperturaCopyright = 32;
  public static final int CierreImageobject = 73;
  public static final int CierreComment = 25;
  public static final int CierreAbstract = 27;
  public static final int AperturaLink = 54;
  public static final int AperturaState = 38;
  public static final int AperturaEntrytbl = 68;
  public static final int Texto = 78;
  public static final int AperturaInfo = 19;
  public static final int EOF = 0;
  public static final int CierreTfoot = 61;
  public static final int AperturaMediaObject = 7;
  public static final int AperturaTitulo = 79;
  public static final int CierreSimPara = 10;
  public static final int AperturaDate = 5;
  public static final int CierrePhone = 41;
  public static final int CierreCopyright = 33;
  public static final int AperturaTgroup = 56;
  public static final int AperturaEntry = 66;
  public static final int CierreAuthor = 31;
  public static final int error = 1;
  public static final int AperturaItemizedList = 17;
  public static final int AperturaSimPara = 11;
  public static final int AperturaRow = 64;
  public static final int AperturaEmail = 42;
  public static final int AperturaComment = 24;
  public static final int CierreState = 39;
  public static final int CierreMediaObject = 6;
  public static final int AperturaVideoobject = 70;
  public static final int CierreYear = 49;
  public static final int CierreSimpleSect = 29;
  public static final int AperturaStreet = 34;
}

