
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 29 23:01:26 ART 2023
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CierreDerechos = 30;
  public static final int AperturaDerechos = 29;
  public static final int AperturaComentario = 21;
  public static final int AperturaTablaInformal = 19;
  public static final int Encabezado = 2;
  public static final int AperturaImportante = 11;
  public static final int CierreTablaInformal = 20;
  public static final int CierreDireccion = 16;
  public static final int CierreSeccionSimple = 26;
  public static final int AperturaListaPuntos = 9;
  public static final int ERROR = 32;
  public static final int CierreParrafo = 14;
  public static final int CierreTitulo = 8;
  public static final int CierreListaPuntos = 10;
  public static final int ArticleCierre = 4;
  public static final int AperturaParrafo = 13;
  public static final int Texto = 31;
  public static final int CierreObjetoMedios = 18;
  public static final int CierreFecha = 28;
  public static final int CierreComentario = 22;
  public static final int CierreResumen = 24;
  public static final int EOF = 0;
  public static final int AperturaSeccionSimple = 25;
  public static final int AperturaResumen = 23;
  public static final int CierreImportante = 12;
  public static final int ArticleApertura = 3;
  public static final int error = 1;
  public static final int AperturaDireccion = 15;
  public static final int AperturaInfo = 5;
  public static final int CierreInfo = 6;
  public static final int AperturaFecha = 27;
  public static final int AperturaObjetoMedios = 17;
  public static final int AperturaTitulo = 7;
}

