
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 20 15:22:21 ART 2023
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AperturaTbody = 63;
  public static final int UndefinedToken = 84;
  public static final int CierreEntry = 68;
  public static final int CierreSection = 22;
  public static final int Imagedata = 76;
  public static final int CierreRow = 66;
  public static final int Linea = 80;
  public static final int CierreTitulo = 20;
  public static final int AperturaThead = 59;
  public static final int CierreSurname = 49;
  public static final int EncabezadoXML = 83;
  public static final int AperturaHolder = 52;
  public static final int CierreEmail = 45;
  public static final int CierreTgroup = 58;
  public static final int AperturaYear = 50;
  public static final int CierreCity = 39;
  public static final int AperturaSection = 23;
  public static final int AperturaFirstName = 46;
  public static final int CierrePara = 12;
  public static final int AperturaImageobject = 73;
  public static final int CierreItemizedList = 16;
  public static final int CierreVideoobject = 72;
  public static final int CierreEntrybl = 70;
  public static final int AperturaEmphasis = 54;
  public static final int CierreAddress = 8;
  public static final int Url = 82;
  public static final int CierreInformalTable = 2;
  public static final int Link = 56;
  public static final int CierreEmphasis = 55;
  public static final int AperturaImportant = 15;
  public static final int CierreTbody = 64;
  public static final int AperturaCity = 38;
  public static final int ERROR = 81;
  public static final int AperturaSurname = 48;
  public static final int AperturaAuthor = 32;
  public static final int AperturaSimpleSect = 30;
  public static final int AperturaPara = 13;
  public static final int AperturaTfoot = 61;
  public static final int CierreThead = 60;
  public static final int CierreStreet = 37;
  public static final int AperturaPhone = 42;
  public static final int AperturaArticulo = 24;
  public static final int CierreFirstName = 47;
  public static final int AperturaListItem = 77;
  public static final int CierreInfo = 18;
  public static final int AperturaEntrybl = 69;
  public static final int AperturaInformalTable = 3;
  public static final int CierreArticulo = 25;
  public static final int AperturaAddress = 9;
  public static final int CierreListItem = 78;
  public static final int CierreHolder = 53;
  public static final int CierreDate = 4;
  public static final int Videodata = 75;
  public static final int AperturaAbstract = 28;
  public static final int CierreImportant = 14;
  public static final int AperturaCopyright = 34;
  public static final int CierreImageobject = 74;
  public static final int CierreComment = 27;
  public static final int CierreAbstract = 29;
  public static final int AperturaState = 40;
  public static final int Texto = 79;
  public static final int AperturaInfo = 19;
  public static final int EOF = 0;
  public static final int CierreTfoot = 62;
  public static final int AperturaMediaObject = 7;
  public static final int AperturaTitulo = 21;
  public static final int CierreSimPara = 10;
  public static final int AperturaDate = 5;
  public static final int CierrePhone = 43;
  public static final int CierreCopyright = 35;
  public static final int AperturaTgroup = 57;
  public static final int AperturaEntry = 67;
  public static final int CierreAuthor = 33;
  public static final int error = 1;
  public static final int AperturaItemizedList = 17;
  public static final int AperturaSimPara = 11;
  public static final int AperturaRow = 65;
  public static final int AperturaEmail = 44;
  public static final int AperturaComment = 26;
  public static final int CierreState = 41;
  public static final int CierreMediaObject = 6;
  public static final int AperturaVideoobject = 71;
  public static final int CierreYear = 51;
  public static final int CierreSimpleSect = 31;
  public static final int AperturaStreet = 36;
}

